[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["echo 'No dependencies to install - using Python standard library only'"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "python main.py"
